name: Deploy app-ui

on: 
  push:
    branches:
      - main
    paths:
      - 'app-ui/**'
      - '.github/workflows/app-ui.yml'

  workflow_dispatch:

env:
  NODE_VERSION: '22'

jobs:
  build:
    name: Build App UI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app-ui

    outputs:
      build-path: ${{ steps.set-output.outputs.build-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Set output path
        id: set-output
        run: echo "build-path=dist" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-ui
          path: app-ui/dist

  deploy:
    name: Deploy to dev-eventfoto-ui
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-ui
          path: dist

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_BUSH_087F4A503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
  
