name: Deploy app-ui

on: 
  push:
    branches:
      - main
    paths:
      - 'app-ui/**'
      - '.github/workflows/app-ui.yml'

  workflow_dispatch:

env:
  NODE_VERSION: '22'
  APP_BASE_URL: ${{ vars.APP_BASE_URL }}
  APP_API_BASE_URL: ${{ vars.APP_API_BASE_URL }}
  APP_AUTH_CLIENT_ID: ${{ vars.APP_AUTH_CLIENT_ID }}
  APP_AUTH_AUTHORITY: ${{ vars.APP_AUTH_AUTHORITY }}
  APP_GROUPS_PHOTOGRAPHER_ID: ${{ vars.GROUPS_PHOTOGRAPHER_ID }}
  APP_GROUPS_EVENT_ADMIN_ID: ${{ vars.GROUPS_EVENT_ADMIN_ID }}
  APP_GROUPS_SYSTEM_ADMIN_ID: ${{ vars.GROUPS_SYSTEM_ADMIN_ID }}
  APP_PROCESSING_ARCHIVE_CONTAINER: ${{ vars.PROCESSING_ARCHIVE_CONTAINER }}
  APP_WATERMARK_CONTAINER: ${{ vars.AZURE_STORAGE_WATERMARK_CONTAINER }}

jobs:
  build:
    name: Build App UI
    runs-on: ubuntu-latest
    environment: DEV

    defaults:
      run:
        working-directory: app-ui

    outputs:
      build-path: ${{ steps.set-output.outputs.build-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Set output path
        id: set-output
        run: echo "build-path=dist" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-ui
          path: app-ui/dist

  deploy:
    name: Deploy to dev-eventfoto-ui
    runs-on: ubuntu-latest
    needs: build
    environment: DEV

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-ui
          path: dist

      - name: Generate environment.json
        run: |
          cat <<EOF > dist/event-foto-app-ui/browser/environment.json
          {
            "baseUrl": "${{ env.APP_BASE_URL }}",
            "apiBaseUrl": "${{ env.APP_API_BASE_URL }}",
            "archiveDownloadsContainer": "${{ env.APP_PROCESSING_ARCHIVE_CONTAINER }}",
            "watermarksContainer": "${{ env.APP_WATERMARK_CONTAINER }}",
            "auth": {
              "clientId": "${{ env.APP_AUTH_CLIENT_ID }}",
              "authority": "${{ env.APP_AUTH_AUTHORITY }}"
            },
            "groups": {
              "photographers": "${{ env.APP_GROUPS_PHOTOGRAPHER_ID }}",
              "eventAdministrators": "${{ env.APP_GROUPS_EVENT_ADMIN_ID }}",
              "systemAdministrators": "${{ env.APP_GROUPS_SYSTEM_ADMIN_ID }}"
            }
          }
          EOF

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_UI_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist/event-foto-app-ui/browser"
  
