name: Deploy EventFoto.Processor

on:
  push:
    branches: [ main ]
    paths:
      - 'EventFoto/**'
      - '.github/workflows/eventfoto.processor.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './EventFoto/EventFoto.Processor'
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Function App
        run: |
          dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ./output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: ./output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: DEV
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp
          path: ./output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F5BBCA479D7F4BBEBAC9F3C37660F5B5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A11E04A231864AFF91B65A362A388934 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_037F57C7440147B58877A28A85162F82 }}

      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'dev-eventfoto-processor'
          slot-name: 'Production'
          package: './output'

      - name: Set environment variables
        uses: azure/cli@v1
        with:
          inlineScript: |
            az functionapp config appsettings set \
              --name dev-eventfoto-processor \
              --resource-group dev-eventfoto \
              --settings \
              ConnectionStrings__Database="@Microsoft.KeyVault(SecretUri=https://dev-eventfoto-keyvault.vault.azure.net/secrets/DatabaseConnectionString/)" \
              AzureStorage__ConnectionString="@Microsoft.KeyVault(SecretUri=https://dev-eventfoto-keyvault.vault.azure.net/secrets/StorageContainerConnectionString/)" \
              AzureStorage__ProcessingQueueName="${{ vars.AZURE_STORAGE_PROCESSING_QUEUE }}" \
              ImageProcessorOptions__AuthorizationKey="@Microsoft.KeyVault(SecretUri=https://dev-eventfoto-keyvault.vault.azure.net/secrets/ApiAuthorizationKey/)" \
              ImageProcessorOptions__ThumbnailSize="${{ vars.PROCESSING_THUMBNAIL_SIZE }}" \
              ImageProcessorOptions__ThumbnailUploadEndpoint="${{ vars.PROCESSING_THUMBNAIL_ENDPOINT }}"
