name: Deploy EventFoto.Processor

on:
  push:
    branches: [ main ]
    paths:
      - 'EventFoto/EventFoto/EventFoto.sln'
      - 'EventFoto/EventFoto.Core/**'
      - 'EventFoto/EventFoto.Data/**'
      - 'EventFoto/EventFoto.Processor/**'
      - '.github/workflows/eventfoto.processor.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './EventFoto/EventFoto.Processor'
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Function App
        run: |
          dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ./eventfoto-processor

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: processor
          path: ./eventfoto-processor

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: DEV
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: processor
          path: ./eventfoto-processor

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PROCESSOR }}

      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        id: deploy-to-function-app
        with:
          app-name: 'dev-eventfoto-processor'
          package: './eventfoto-processor'

      - name: Set environment variables
        uses: azure/cli@v1
        with:
          inlineScript: |
            az functionapp config appsettings set \
              --name dev-eventfoto-processor \
              --resource-group dev-eventfoto \
              --settings \
              ConnectionStrings__Database="@Microsoft.KeyVault(SecretUri=https://dev-eventfoto-keyvault.vault.azure.net/secrets/DatabaseConnectionString/)" \
              AzureStorage__ConnectionString="@Microsoft.KeyVault(SecretUri=https://dev-eventfoto-keyvault.vault.azure.net/secrets/StorageContainerConnectionString/)" \
              AzureStorage__ProcessingQueueName="${{ vars.AZURE_STORAGE_PROCESSING_QUEUE }}" \
              ImageProcessorOptions__ThumbnailSize="${{ vars.PROCESSING_THUMBNAIL_SIZE }}"
