name: Run Migrations

on:
  workflow_dispatch:


jobs:
  migrate:
    environment: DEV
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_IDENTITY_CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          allow-no-subscriptions: true

      - name: Fetch secret from Key Vault
        id: getsecret
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ vars.KEYVAULT_NAME }}
          secrets: ${{ vars.DATABASE_CONNECTION_SECRET_NAME }}

      - name: Build the application
        run: dotnet build EventFoto/EventFoto.Data.Migrator/EventFoto.Data.Migrator.csproj --configuration Release

      - name: Run the application
        run: dotnet run --project EventFoto/EventFoto.Data.Migrator/EventFoto.Data.Migrator.csproj
        env:
          ConnectionStrings__Database: ${{ steps.getsecret.outputs[vars.DATABASE_CONNECTION_SECRET_NAME] }}
